config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'deadlines#calendar'
  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }
  resources :deadlines
  resources :study_preferences
  resources :study_times
  post 'study_times/create_all_study_times'
  resources :date_ranges do
    resources :time_preferences
  end

  resources :signup
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/study_preference.rb
# frozen_string_literal: true

class StudyPreference < ApplicationRecord
  belongs_to :deadline

  validates :priority, presence: true
  validates :requiredTime, presence: true
  validates :deadline, presence: true
end

app/controllers/study_preferences_controller.rb
# frozen_string_literal: true

# Controller for Study Preferences
class StudyPreferencesController < ApplicationController
  def index
    @study_preferences = StudyPreference.all
  end

  def show
    @study_preference = StudyPreference.find(params[:id])
  end

  def new
    @study_preference = StudyPreference.new
  end

  def create
    @study_preference = StudyPreference.new(study_preference_params)

    if @study_preference.save
      redirect_to @study_preference
    else
      render :new
    end
  end

  def edit
    @study_preference = StudyPreference.find(params[:id])
  end

  def update
    @study_preference = StudyPreference.find(params[:id])

    if @study_preference.update(study_preference_params)
      redirect_to @study_preference
    else
      render :edit
    end
  end

  def destroy
    @study_preference = StudyPreference.find(params[:id])
    @study_preference.destroy

    redirect_to study_preferences_path
  end

  private

  def study_preference_params
    params.require(:study_preference).permit(:deadline_id, :priority, :requiredTime)
  end
end

app/helpers/study_preferences_helper.rb
# frozen_string_literal: true

# Study Preferences helper
module StudyPreferencesHelper
end

app/views/study_preferences/_form.html.erb
<%= form_with model: @study_preference do |form| %>

  <div>
    <div>
      <div>
        <%= form.label :deadline %><br>
        <% if  @study_preference.persisted?%>
          <%= form.collection_select :deadline_id, Deadline.where(:study_preference == @study_preference), :id, :name, class: "form-control" %>
        <% else %>
          <%= form.collection_select :deadline_id, Deadline.where.missing(:study_preference), :id, :name, class: "form-control"%>
        <% end %>
        <% @study_preference.errors.full_messages_for(:deadline).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <br>

      <div>
        <%= form.label :priority, "Priority for the Deadline " %><br>
        <%= form.number_field :priority, in: 1.0..10.0, step: 1, class: "form-control" %>
        <%# TODO Show visual feedback on importance level %>
        <% @study_preference.errors.full_messages_for(:priority).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <br>

      <div>
        <%= form.label :requiredTime, "Required Time in Minutes (Min 30-Max 720)" %><br>
        <%= form.number_field :requiredTime, in: 30.0..720.0, step: 30, class: "form-control"%>
        <% @study_preference.errors.full_messages_for(:requiredTime).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <br>
        <%= form.submit class: "btn btn-success"%>
    <% end %>
    </div>
  </div>

app/views/study_preferences/edit.html.erb
<% content_for :page_title do %>
  Edit Study Preference
<% end %>

<%= render "form", study_preference: @study_preference %>

app/views/study_preferences/index.html.erb
<% content_for :page_title do %>
  Study Preferences
<% end %>

<ul>
  <% @study_preferences.each do |study_preference| %>
    <li>
      <%= link_to study_preference.deadline.name, study_preference %>
    </li>
  <% end %>
</ul>
<%= link_to "New Study Preference", new_study_preference_path, class: "btn btn-success" %>

app/views/study_preferences/new.html.erb
<% content_for :page_title do %>
  New Study Preference
<% end %>

<%= render "form", study_preference: @study_preference %>

app/views/study_preferences/show.html.erb
<% content_for :page_title do %>
  <strong>Study Preference for Deadline: </strong><%= @study_preference.deadline.name %>
<% end %>

<p> <strong>Level of Priority: </strong><%=@study_preference.priority%></p>
<p><strong>Required Time: </strong><%=  @study_preference.requiredTime%></p>

<ul>
  <li><%= link_to "Go to Deadline", deadline_path(@study_preference.deadline) %></li> 
  <li><%= link_to "Study Preferences", study_preferences_path %></li>
  <li><%= link_to "Edit", edit_study_preference_path(@study_preference) %></li>
  <li><%= link_to "Destroy", study_preference_path(@study_preference),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>