config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'deadlines#calendar'
  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }
  resources :deadlines
  resources :study_preferences
  resources :study_times
  post 'study_times/create_all_study_times'
  resources :date_ranges do
    resources :time_preferences
  end

  resources :signup
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/deadline.rb
# frozen_string_literal: true

# Represents a deadline on the calendar
class Deadline < ApplicationRecord
  has_one :study_preference, dependent: :destroy
  has_many :study_time, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :date, presence: true

  ##
  # Alias date to start_time so that we can integrate seamlessly with simple
  # calendar https://github.com/excid3/simple_calendar#rendering-events
  def start_time
    date
  end
end

app/controllers/deadlines_controller.rb
# frozen_string_literal: true

# Controller for Deadlines
class DeadlinesController < ApplicationController
  def index
    @deadlines = Deadline.all
  end

  # https://github.com/excid3/simple_calendar#rendering-events
  def calendar
    date = params.fetch(:start_date, Time.zone.today).to_date
    @deadlines = Deadline.where(date: date.beginning_of_month.beginning_of_week..date.end_of_month.end_of_week)
  end

  def show
    @deadline = Deadline.find(params[:id])
  end

  def new
    @deadline = Deadline.new
  end

  def create
    @deadline = Deadline.new(deadline_params)

    if @deadline.save
      redirect_to @deadline
    else
      render :new
    end
  end

  def edit
    @deadline = Deadline.find(params[:id])
  end

  def update
    @deadline = Deadline.find(params[:id])

    if @deadline.update(deadline_params)
      redirect_to @deadline
    else
      render :edit
    end
  end

  def destroy
    @deadline = Deadline.find(params[:id])
    @deadline.destroy

    redirect_to deadlines_path
  end

  private

  def deadline_params
    params.require(:deadline).permit(:name, :description, :date)
    #params.require(:deadline).permit(:name, :description, :date, :color)
  end
end

app/helpers/deadlines_helper.rb
# frozen_string_literal: true

# Deadline Helper
module DeadlinesHelper
end

app/views/deadlines/_form.html.erb
<%= form_with model: @deadline do |form| %>
  <div>
    <div>
      <form>
        <div>
          <%= form.label :name %><br>
          <%= form.text_field :name, class: "form-control" %>
          <% @deadline.errors.full_messages_for(:name).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
        <br>

        <div>
          <%= form.label :description %><br>
          <%= form.text_area :description, class: "form-control" %>
          <% @deadline.errors.full_messages_for(:description).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
        <br>

        <div>
          <%= form.label :date %><br>
          <%= form.datetime_select :date, class: "form-control" %>
          <% @deadline.errors.full_messages_for(:date).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
        <br>

        <div>
          <%= form.label :color %><br>
          <%= form.color_field :color, value: "000" %>
        </div>

        <br>
        <br>
        <%= form.submit class: "btn btn-success" %>
      </form>
    </div>
  </div>
<% end %>

app/views/deadlines/calendar.html.erb
<style>
a:link {
  text-decoration: none;
}

a:visited {
  text-decoration: none;
}
</style>
<%= month_calendar(events: @deadlines) do |date, deadlines| %>
  <%= date.day %>
  <ul>
    <% deadlines.each do |deadline| %>
      <div style="color: <%= deadline.color%>">
        <li>
          <%= link_to deadline.name, deadline_path(deadline), style: "color: inherit;" %>
        </li>
      </div>
    <% end %>
  </ul>
<% end %>

<%= link_to "New Deadline", new_deadline_path%>
<%= link_to "Study Preferences", study_preferences_path%>

app/views/deadlines/edit.html.erb
<% content_for :page_title do %>
  Edit Deadline
<% end %>

<%= render "form", deadline: @deadline %>

app/views/deadlines/index.html.erb
<table>
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Date</th>
      <th scope="col">Last Updated</th>
      <th></th>
      <th></th>

    </tr>
  </thead>
  <tbody>
    <% @deadlines.each do |deadline| %>
      <tr>
        <th scope="row">
          <%= deadline.name %>
        </th>
        <td>
          <%= deadline.description %>
        </td>
        <td>
          <%= deadline.date.to_formatted_s(:long) %>
        </td>
        <td>
          <%= deadline.updated_at.to_formatted_s(:long) %>
        </td>
        <td>
          <%= link_to "Edit", edit_deadline_path(deadline) %>
        </td>
        <td>
          <%= link_to "Delete", deadline_path(deadline), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Deadline", new_deadline_path, class: "btn btn-success" %>
<%= link_to "Study Preferences", study_preferences_path, class: "btn btn-primary" %>

app/views/deadlines/new.html.erb
<% content_for :page_title do %>
  New Deadline
<% end %>

<%= render "form", deadline: @deadline %>

app/views/deadlines/show.html.erb
<% content_for :page_title do %>
  <%= @deadline.name %>
<% end %>

<p><%= @deadline.description %></p>
<p><%= @deadline.date %></p>

<ul>
  <% if  @deadline.study_preference != nil%>
      <li><%= link_to "Go to Study Preference", study_preference_path(@deadline.study_preference) %></li>
  <% else %>
      <li><%= link_to "Go to Study Preferences", study_preferences_path %></li>
  <% end %>
  <li><%= link_to "Deadlines", deadlines_path %></li>
  <li><%= link_to "Edit", edit_deadline_path(@deadline) %></li>
  <li><%= link_to "Destroy", deadline_path(@deadline),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>