config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'deadlines#calendar'
  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }
  resources :deadlines
  resources :study_preferences
  resources :study_times
  post 'study_times/create_all_study_times'
  resources :date_ranges do
    resources :time_preferences
  end

  resources :signup
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/date_range.rb
# frozen_string_literal: true

class DateRange < ApplicationRecord
  has_many :time_preferences, dependent: :destroy

  validates :name, presence: true
  validates :start, presence: true
  validates :end, presence: true
end

app/controllers/date_ranges_controller.rb
# frozen_string_literal: true

# Controller for Date Ranges
class DateRangesController < ApplicationController
  def index
    @date_ranges = DateRange.all
  end

  def show
    @date_range = DateRange.find(params[:id])
  end

  def new
    @date_range = DateRange.new
  end

  def create
    @date_range = DateRange.new(date_range_params)

    if @date_range.save
      redirect_to @date_range
    else
      render :new
    end
  end

  def edit
    @date_range = DateRange.find(params[:id])
  end

  def update
    @date_range = DateRange.find(params[:id])

    if @date_range.update(date_range_params)
      redirect_to @date_range
    else
      render :edit
    end
  end

  def destroy
    @date_range = DateRange.find(params[:id])
    @date_range.destroy

    redirect_to date_ranges_path
  end

  private

  def date_range_params
    params.require(:date_range).permit(:name, :start, :end)
  end
end

app/helpers/date_ranges_helper.rb
# frozen_string_literal: true

# Date Ranges Helper
module DateRangesHelper
end

app/views/date_ranges/_form.html.erb
<%= form_with model: @date_range do |form| %>

<form>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @date_range.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
  <br>
    <%= form.label :start %><br>
    <%= form.date_select :start %>
    <% @date_range.errors.full_messages_for(:start).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
  <br>
    <%= form.label :end %><br>
    <%= form.date_select :end %>
    <% @date_range.errors.full_messages_for(:end).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  
  <div>
  <br>
  <div>
      <div>
        <div>
          <%= link_to 'Back', :back %>
        </div>
      </div>
      <div>
        <div>
          <%= form.submit %>
      </div>
    </div>
  </div>


  </form>
  </body>
<% end %>

app/views/date_ranges/edit.html.erb
<% content_for :page_title do %>
  Edit Deadline
<% end %>

<%= render "form", date_range: @date_range %>

app/views/date_ranges/index.html.erb
<% content_for :page_title do %>
  Date Ranges
<% end %>

<ul>
  <% @date_ranges.each do |date_range| %>
    <li>
      <%= link_to date_range.name, date_range %>
      <%= date_range.start %>
      <%= date_range.end %>
    </li>
  <% end %>
</ul>

<%= link_to "New Date Range", new_date_range_path %>

app/views/date_ranges/new.html.erb
<% content_for :page_title do %>
  New Date Range
<% end %>

<%= render "form", date_range: @date_range %>

app/views/date_ranges/show.html.erb
<% content_for :page_title do %>
  <%= @date_range.name %>
<% end %>

<p><%= @date_range.start %></p>
<p><%= @date_range.end %></p>

<ul>
  <li><%= link_to "Date Ranges", date_ranges_path %></li>
  <li><%= link_to "Edit", edit_date_range_path(@date_range) %></li>
  <li><%= link_to "Destroy", date_range_path(@date_range),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

<h2>Time Preferences</h2>
<% @date_range.time_preferences.each do |time_preference| %>
  <p>
    <strong>Name:</strong>
    <%= time_preference.name %>
  </p>

  <p>
    <strong>Available:</strong>
    <%= time_preference.available %>
  </p>

  <p>
    <strong>Day of The Week:</strong>
    <%= time_preference.dayOfWeek %>
  </p>

  <p>
    <strong>Start Time:</strong>
    <%= time_preference.start.strftime("at %I:%M%p") %>
  </p>

  <p>
    <strong>End Time:</strong>
    <%= time_preference.end.strftime("at %I:%M%p") %>
  </p>

  <p>
  <%= link_to 'Destroy Time Preference', [time_preference.date_range, time_preference],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>
<% end %>

<h2>Add a time preference:</h2>
<%= form_with model: [ @date_range, @date_range.time_preferences.build ] do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.radio_button :available, 1 %>
    <%= form.label :available, "I am available" %>
    <%= form.radio_button :available, 0 %>
    <%= form.label :available, "I am not available" %>
  </p>
   <p>
    <%= form.select :dayOfWeek, ["Monday", "Tuesday", "Wednsday","Thursday","Friday","Saturday","Sunday"] %>
  </p>
  <p>
    <%= form.label :start %><br>
    <%= form.time_select :start %>
  </p>
  <p>
    <%= form.label :end %><br>
    <%= form.time_select :end %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>